name: build image
on:
  push:
    paths:
      - 'Dockerfile'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_SERVICE_ACCOUNT_GITHIB_ACTION_KEY }}

      - name: setup docker context for buildx
        run: |
          docker context create builders

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: us.gcr.io/ridecell-1/
          tags: |
            type=raw,value={{date 'X'}}-{{branch}}-{{sha}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}