name: build image
on:
  push:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    env:
      TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
    steps:
      - name: Setup go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install lint
        run: |
          # binary will be $(go env GOPATH)/bin/golangci-lint
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.44.2
      - name: Run lint
        run: |
          golangci-lint run --timeout 5m

  docker:
    runs-on: ubuntu-20.04
    needs: [lint]
    if: ${{ github.ref == 'refs/heads/main'|| contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE') }}
    steps:
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_SERVICE_ACCOUNT_GITHIB_ACTION_KEY }}

      - name: setup docker context for buildx
        run: |
          docker context create builders

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: us.gcr.io/ridecell-1/k8s-scheduler-extender
          tags: |
            type=raw,value={{date 'X'}}-{{branch}}-{{sha}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}